### ISSUE TITLE
Typo in Cumulative Angular Displacements?

### ISSUE THREAD

**Issue by brcolow** [ballen4705/Moody-Method#1]
Hi There,

First of all thanks very much for publishing this awesome work.

I am trying to go through and understand the work and I noticed one thing which, at first glance, seems like a typo:

https://github.com/ballen4705/Moody-Method/blob/01560b10c09c8013eacf150226c99786a094b4eb/moody.c#L369-L370

Should it not be corrected to:

```c
for (j=2; j<=ndat; j++) ws[which_sheet][3][j]=
			 ws[which_sheet][3][j-1]+ws[which_sheet][3][j];
```

Thanks again!

**Comment by brcolow** [comment]
Sorry, I realized I was mistaken.

**Comment by ballen4705** [comment]
Hi Michael,

Sorry that I am slow in getting back to you -- I'm on holiday in Italy.

> I am trying to go through and understand the work and I noticed one 
> thing which, at first glance, seems like a typo:
> 
> https://github.com/ballen4705/Moody-Method/blob/01560b10c09c8013eacf150226c99786a094b4eb/moody.c#L369-L370 
> <https://github.com/ballen4705/Moody-Method/blob/01560b10c09c8013eacf150226c99786a094b4eb/moody.c#L369-L370>
> 
> Should it not be corrected to:
> 
> for  (j=2; j<=ndat; j++) ws[which_sheet][3][j]=
> 			 ws[which_sheet][3][j-1]+ws[which_sheet][3][j];

I've attached the relevant snippet of Moody's paper (item 2).

I think that my code is correct.  Your version can not be correct, 
because on the right-hand-side of the equality, you do not make any
reference to the data contained in Moody's column 3, which is the data 
ws[which_sheet][2][*].

Please note that:
Moody column 1 is stored in ws[which_sheet][0][*]
Moody column 2 is stored in ws[which_sheet][1][*]
Moody column 3 is stored in ws[which_sheet][2][*]
Moody column 4 is stored in ws[which_sheet][3][*]

Cheers,
	Bruce
